<#
.SYNOPSIS
  Builds FRENCH_REVIEW.md from the shipped DefInjected XML, for TRANSLATIONS.md's
  "Systematic French review by Virginie" (2026-09-30).
.DESCRIPTION
  This mod has no Keyed strings: every player-facing text is a DefInjected field. French
  and English are both one file per def type (Mod/Languages/{French,English}/DefInjected/
  <DefType>/WA.xml), so English is resolved by matching relative path.

  Original: WA is a Chinese-authored mod (see LICENSE/STATUS.md research); the game's own
  Defs under Mod/Defs carry their label/description in English, not Chinese, so English is
  not a stand-in for the original the way FoodCourt's Chinese source is. The true original
  text is the ChineseSimplified DefInjected tree, which exists (ChineseTraditional is a
  script conversion of it, not an independent source) but is split across many small files
  per category rather than one file per def type, so it is merged by key across every file
  under Mod/Languages/ChineseSimplified/DefInjected/<DefType>/*.xml instead of by filename.
#>
param(
    [string]$Root = (Split-Path $PSScriptRoot -Parent),
    [string]$OutFile = (Join-Path (Split-Path $PSScriptRoot -Parent) 'FRENCH_REVIEW.md')
)

function Get-Entries($path) {
    $entries = [ordered]@{}
    if (-not (Test-Path $path)) { return $entries }
    $xml = [xml](Get-Content $path -Raw -Encoding UTF8)
    foreach ($node in $xml.LanguageData.ChildNodes) {
        if ($node.NodeType -ne 'Element') { continue }
        $entries[$node.Name] = $node.InnerText
    }
    return $entries
}

function Get-MergedEntries($dir) {
    $entries = [ordered]@{}
    if (-not (Test-Path $dir)) { return $entries }
    Get-ChildItem $dir -Filter *.xml | Sort-Object Name | ForEach-Object {
        $sub = Get-Entries $_.FullName
        foreach ($k in $sub.Keys) { $entries[$k] = $sub[$k] }
    }
    return $entries
}

# Read by hand, 2026-09-30 (TRANSLATIONS.md's gender-agreement rule): two texts carry a past
# participle that agrees with whichever pawn the aura hediff lands on, in the masculine only,
# with no {PAWN_gender ? ...} switch. Both are duplicated across several keys (five identical
# stage labels for the princess's hediff, one for the yokozuna's).
$ManualFlags = @{
    'HDA_Hediff_EncouragementOfThePrincess.stages.I_was_encouraged_by_the_princess-0.label' = "encouragé agrees masculine only; the wearer's aura can land on a pawn of any gender"
    'HDA_Hediff_EncouragementOfThePrincess.stages.I_was_encouraged_by_the_princess-1.label' = "encouragé agrees masculine only; the wearer's aura can land on a pawn of any gender"
    'HDA_Hediff_EncouragementOfThePrincess.stages.I_was_encouraged_by_the_princess-2.label' = "encouragé agrees masculine only; the wearer's aura can land on a pawn of any gender"
    'HDA_Hediff_EncouragementOfThePrincess.stages.I_was_encouraged_by_the_princess-3.label' = "encouragé agrees masculine only; the wearer's aura can land on a pawn of any gender"
    'HDA_Hediff_EncouragementOfThePrincess.stages.I_was_encouraged_by_the_princess-4.label' = "encouragé agrees masculine only; the wearer's aura can land on a pawn of any gender"
    'HDA_Hediff_IntimidateOfTheYokozuna.stages.Overwhelmed_by_the_Yokozuna.label' = 'Intimidé agrees masculine only; the target of the aura can be a pawn of any gender'
}

$frenchRoot = Join-Path $Root 'Mod/Languages/French/DefInjected'
$englishRoot = Join-Path $Root 'Mod/Languages/English/DefInjected'
$chineseRoot = Join-Path $Root 'Mod/Languages/ChineseSimplified/DefInjected'

$frenchFiles = Get-ChildItem $frenchRoot -Recurse -Filter *.xml | Sort-Object FullName
$out = New-Object System.Text.StringBuilder
[void]$out.AppendLine("# French review")
[void]$out.AppendLine()
[void]$out.AppendLine("Generated by `_tools/Generate-FrenchReview.ps1` for TRANSLATIONS.md's systematic French review.")
[void]$out.AppendLine("This mod has no Keyed strings, only DefInjected. **Original column: the ChineseSimplified")
[void]$out.AppendLine("DefInjected text**, WA being a Chinese-authored mod; the Defs' own native fields are English,")
[void]$out.AppendLine("not the source language, so English cannot stand in for Original here the way it does for a")
[void]$out.AppendLine("mod whose Defs carry the source text natively. Chinese is merged by key across every file in")
[void]$out.AppendLine("the def type's ChineseSimplified folder, since that language splits one file per category")
[void]$out.AppendLine("where French and English each keep one file per def type.")
[void]$out.AppendLine()
[void]$out.AppendLine("Generated $(Get-Date -Format 'yyyy-MM-dd'), revision: working tree after the anchor/pirate-faction/wait-margin fixes of 2026-09-29.")
[void]$out.AppendLine()

foreach ($ff in $frenchFiles) {
    $rel = $ff.FullName.Substring($frenchRoot.Length + 1) -replace '\\', '/'
    $defType = ($rel -split '/')[0]
    $frEntries = Get-Entries $ff.FullName
    if ($frEntries.Count -eq 0) { continue }

    $enPath = Join-Path $englishRoot $rel
    $enEntries = Get-Entries $enPath
    $zhEntries = Get-MergedEntries (Join-Path $chineseRoot $defType)

    [void]$out.AppendLine("## DefInjected/$rel")
    [void]$out.AppendLine()
    [void]$out.AppendLine("| Key or path | Original (Chinese) | English | French | Flag |")
    [void]$out.AppendLine("|---|---|---|---|---|")
    foreach ($key in $frEntries.Keys) {
        $fr = $frEntries[$key]
        $orig = $null
        if ($zhEntries.Contains($key)) { $orig = $zhEntries[$key] }
        $en = $null
        if ($enEntries.Contains($key)) { $en = $enEntries[$key] }
        if ($null -eq $orig) { $orig = '*(not found in ChineseSimplified — check by hand)*' }
        if ($null -eq $en) { $en = '*(not found — check by hand)*' }
        $auto = $fr -match '\?\?\?|TODO' -or ($fr -match '\{PAWN_gender' -and $fr -notmatch '\{PAWN_gender \? ')
        $origCell = ($orig -replace '\|', '\|') -replace "`n", ' '
        $enCell = ($en -replace '\|', '\|') -replace "`n", ' '
        $frCell = ($fr -replace '\|', '\|') -replace "`n", ' '
        $keyCell = $key -replace '\|', '\|'
        if ($ManualFlags.ContainsKey($key)) {
            [void]$out.AppendLine("| $keyCell | $origCell | $enCell | $frCell | ? — $($ManualFlags[$key]) |")
        } elseif ($auto) {
            [void]$out.AppendLine("| $keyCell | $origCell | $enCell | $frCell | ? |")
        } else {
            [void]$out.AppendLine("| $keyCell | $origCell | $enCell | $frCell | |")
        }
    }
    [void]$out.AppendLine()
}

[System.IO.File]::WriteAllText($OutFile, $out.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Output "wrote $OutFile"
